name: CloudApp Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Package application
        run: mvn package -Dmaven.test.skip
      - name: Create deployment folder
        run: |
          mkdir -p CloudAppRelease && cp ./target/cloud.app-0.0.1-SNAPSHOT.jar CloudAppRelease/cloud.app-0.0.1-SNAPSHOT.jar &&
          cp ./application.properties CloudAppRelease/application.properties && cp ./users.csv CloudAppRelease/users.csv
      - name: Create zip of deployment folder
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r CloudAppRelease.zip CloudAppRelease
      - name: Run `packer init`
        id: init
        run: "packer init aws-ec2.pkr.hcl"
      - name: Run `packer build`
        id: build
        run: "packer build aws-ec2.pkr.hcl"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
          AWS_DEFAULT_SUBNET: ${{ vars.AWS_DEFAULT_SUBNET }}
