name: CloudApp Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Setup PostgreSQL Server
        uses: ikalnytskyi/action-setup-postgres@v4
        with:
          username: hariharansundaram
          password: gautham123
          database: hariharansundaram
          port: 5432
        id: postgres
      - name: Build instance
        run: mvn install
      - name: Run `packer init`
        id: init
        run: "packer init ."
      - name: Run `packer build`
        id: build
        run: "packer build ."