# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: CloudApp CI

on:
  push:
    branches: [ "main", "create_packer" ]
  pull_request:
    branches: [ "main", "create_packer" ]

env:
  PRODUCT_VERSION: "1.9.4"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    - name: Setup PostgreSQL Server
      uses: ikalnytskyi/action-setup-postgres@v4
      with:
        username: hariharansundaram
        password: gautham123
        database: hariharansundaram
        port: 5432
      id: postgres

    - name: Build with Maven
      run: mvn compile

    - name: Test with Maven
      run: mvn test

  packer:
    needs: [ build ]
    runs-on: ubuntu-latest
    name: Test Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Run `packer init`
        id: init
        run: "packer init ."

      - name: Run `packer fmt`
        id: fmt
        run: "packer fmt ."

      - name: Run `packer validate`
        id: validate
        run: "packer validate ."